spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:Discount
    username: boubou
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true



  application:
   name: stockService

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka


server:
  port: 8082
